---
title: "Week 3 Asdos"
author: "Assistant Lecturer-A (Bondan and Kevin)"
date: "3/23/2021"
output: html_document
---

# Bonjour! Everyone 
## Dipelajari Ya!

### Setting Your Diretory First
```{r}
getwd()
```
```{r}
setwd("C:/Users/bonda/OneDrive/Documents/MATKUL STATISTIK/Asdos AED Materi/Week 3")

```

### Read File Using .csv File
```{r}
Data_World_Happy_2018_2019_csv <- read.csv("Data World Happy 2018-2019.csv")

```

### Read File Using Library Readxl
```{r}
library(readxl)
```

Use Read_xlsx For Library(readxl)
```{r}
Data_World_Happy_2018_2019 <- read_xlsx("Data World Happy 2018-2019.xlsx")

```

Filtering Definisi Tahun data

```{r}
Happy_2018 <- Data_World_Happy_2018_2019[Data_World_Happy_2018_2019$Year == 2018, ]

```
```{r}
Happy_2019 <- Data_World_Happy_2018_2019[Data_World_Happy_2018_2019$Year == 2019, ]

```

Melihat Data
```{r}
head(Happy_2018)
```
```{r}
head(Happy_2019)
```

## Scatter Plot
### Basic Scatterplot
For Gdp Vs Score (Year = 2019)
```{r}
plot( Happy_2019$GDP, Happy_2019$Score)
```

For score vs Social Support (Year = 2019)
```{r}
plot( Happy_2019$SocSup, Happy_2019$Score)
```

For Score Vs GDP data 2018 and 2019
```{r}
plot( Data_World_Happy_2018_2019$GDP, Data_World_Happy_2018_2019$Score)

```


### Customized The ScatterPlot
```{r}
plot( Data_World_Happy_2018_2019$GDP, Data_World_Happy_2018_2019$Score,
     xlab = 'GDP World Happiness',
     ylab = 'Score World Happiness',
     col = ifelse(Data_World_Happy_2018_2019$Year == '2018', '#d9ed92',
                                ifelse(Data_World_Happy_2018_2019$Year=='2019', '#99d98c','#168aad')),
     col.lab='#1e6091',
     col.axis= '#1e6091',
     cex.axis = 0.8,
     cex.lab = 0.8,
     font.lab = 2,
     pch = 19,
     frame.plot = F
)

mtext('World Happiness Report Data', side=3, at=-0, adj=0, cex=1.3,
      font = 2, col = '#1e6091')
mtext('Tahun 2018 dan 2019', side=3, at=0, adj=0, cex=0.75, line = -0.88,
      font = 2, col = '#1e6091')

legend(x = 1.5, y = 5, legend = c('2018', '2019'), 
       col = c('#d9ed92', '#99d98c'),
       bty = 'n',
       pch = c(19,19),
       cex = 0.6,
       text.col = '#1e6091'
)

axis(1, col = '#1e6091', col.axis= '#1e6091', cex.axis = 0.8)
axis(2, col = '#1e6091', col.axis= '#1e6091', cex.axis = 0.8, at = seq(0, 10, 1))
```



